# Change these first
owner: themonetizr # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Monetizr API
    url: https://api3.themonetizr.com
  - name: Console
    url: https://api.themonetizr.com
  - name: Homepage
    url: https://themonetizr.com
  - name: Docs
    url: https://docs.themonetizr.com
  - name: Trash Dash Web
    url: https://trash.themonetizr.com
  - name: Tic Tac Toe
    url: https://tutorial.themonetizr.com
  - name: Pacman
    url: https://pacman.themonetizr.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.themonetizr.com
  # baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/19929995?s=400&u=09ff5e444cb162ccdf5dcda6252e6d58a0fc87f4&v=4
  name: Monetizr
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a generated status page displaying status of Monetizr services.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
